version: "3.3"

volumes:
  ssl:
  db:
  phpmyadmin:

networks:
  nginx:

services:
  app:
    image: app
    build:
      context: ./app
      args:
        XDEBUG: ${APP_XDEBUG}
    restart: always
    working_dir: ${APP_WORKDIR}
    volumes:
      - $HOME/.cache/composer:/composer/cache
      - $HOME/.ssh:/home/www-data/.ssh
      - ../$APP_URL:/var/www/project
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
      LIVERELOAD: ${APP_LIVERELOAD}
      # Exposes BLACKFIRE_* environment variables from the host
      BLACKFIRE_SERVER_ID: 91559524-ea2e-4a3d-a203-65b33e1db466
      BLACKFIRE_SERVER_TOKEN: b08540de692d4367476430b87562e7481f3426ca3a641a05dca47a0fff964023
      BLACKFIRE_CLIENT_ID: 95570327-f669-433a-b54d-6b2461e25986
      BLACKFIRE_CLIENT_TOKEN: 7e8565377aa433914be615ddc7771dcbd1d161a6680285dfebdc8f7d0a2ac925
    ports:
      - 35729:35729
      - 25:25
    networks:
      - nginx
    # command: tail -f /dev/null

  nginx:
    image: nginx
    build:
      context: nginx
    restart: always
    volumes:
      - ../$APP_URL:/var/www/project
      - ssl:/etc/letsencrypt
      - phpmyadmin:/var/www/html
    environment:
      APP_URL: ${APP_URL}
      NGINX_ROOT: ${NGINX_ROOT}
    ports:
      - 80:80
      - 443:443
    networks:
      nginx:
        aliases:
          - ${APP_URL}
    # command: tail -f /dev/null

  mariadb:
    image: mariadb:10.5.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME};
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    networks:
      - nginx
    ports:
      - 3306:3306

  redis:
    build: ./redis
    restart: always
    networks:
      - nginx

  blackfire:
    image: blackfire/blackfire
    ports: ["8707"]
    restart: always
    environment:
      BLACKFIRE_SERVER_ID: 91559524-ea2e-4a3d-a203-65b33e1db466
      BLACKFIRE_SERVER_TOKEN: b08540de692d4367476430b87562e7481f3426ca3a641a05dca47a0fff964023
      BLACKFIRE_CLIENT_ID: 95570327-f669-433a-b54d-6b2461e25986
      BLACKFIRE_CLIENT_TOKEN: 7e8565377aa433914be615ddc7771dcbd1d161a6680285dfebdc8f7d0a2ac925
    networks:
      - nginx

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.4-fpm-alpine
    volumes:
      - phpmyadmin:/var/www/html
    restart: always
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_USER: "root"
      PMA_PASSWORD: "secret"
      UPLOAD_LIMIT: 10048M
    networks:
      - nginx

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - nginx
